### PR TITLE
Orion: use system GCC & OpenMPI

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
@climbfuji see what you think-- This would make use of the system-provided GCC and OpenMPI.

### CODE REVIEW

**Comment by climbfuji** [comment]
That's fine with me, but it requires us to remove the `gcc/12` module in the epic modulefiles directory, and I don't know if that will break the existing 1.7.0 installation?

**Comment by AlexanderRichert-NOAA** [comment]
Hrm. Where/when does that get added to $MODULEPATH?

**Comment by climbfuji** [comment]
In the general instructions for the site (needed because of the ecflow module, otherwise we could just remove it).

We *could* create a new modulefiles directory `modulefiles-rocky9` and copy or symlink the ecflow module (I think that is the only one needed), and then update the instructions accordingly?

**Comment by AlexanderRichert-NOAA** [comment]
That sounds good I think. Alternatively we could rename the spack-stack gcc module and update it in the 1.7.0 config?

**Comment by climbfuji** [comment]
I think it's safer to just create a new modulefiles directory - won't break anything. There is also a miniconda module in the existing one that we don't need. Let me do this now ...

**Comment by climbfuji** [comment]
~~Actually, I am going to build a new ecflow - the one in `modulefiles` is still from CentOS! :-( ~~

scrap that, it is not

**Comment by climbfuji** [comment]
```
[role-epic@Orion:/work/noaa/epic/role-epic/spack-stack/orion]$ ls -lart modulefiles-rocky9/
total 48
drwxr-sr-x+  2 role-epic epic 16384 Jun 14 09:30 ecflow
drwxr-sr-x+ 16 role-epic epic 16384 Jul  3 17:50 ..
drwxr-sr-x+  3 role-epic epic 16384 Jul  3 17:50 .
```

**Pull request merged**
